# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Anguler CI Develop branch

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop/**]

jobs:
  build_angular:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # - run: npm ci
      # - run: npm run build

      # - name: Exclude files with testing errors from build
      #   run: .github/scripts/exclude_build.sh

      - name: set the value
        id: step_one
        run: curl https://httpbin.org/json >> response.txt

      - name: echo
        run: cat response.txt

      - name: set the value
        run: echo "TEST=$curl https://httpbin.org/json" >> $GITHUB_ENV

      - name: Debug EOF
        run: echo ${{ env.EOF }}

      # - name: Run end2end test
      #   run: .github/scripts/e2e.sh

      - name: Build the stack
        run: docker-compose up -d

      # - uses: cypress-io/github-action@v2
      #   with:
      #     build: npm run cy:run
      #     wait-on: http://localhost:4200

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_DUNE_01EE1B503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/DrinkBuddy' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Use Node.js 14.15
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: 14.15
    #   - run: npm ci
    #   - name: Exclude files with testing errors from build
    #     run: .github/scripts/exclude_build.sh
