name: Angular CI Feature branch

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [feature/**]

env:
  TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
  TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}

jobs:
  filter_modules:
    name: Filter Modules with testing errors
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15

      - name: Setup
        run: npm ci

      - name: Set CURRENT_BRANCH
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Set PARENT_BRANCH
        run: echo "PARENT_BRANCH=develop" >> $GITHUB_ENV

      - name: Set TIMESTAMP
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Set NEW_BRANCH
        run: echo "NEW_BRANCH=${CURRENT_BRANCH}_SUCCESS_${TIMESTAMP}" >> $GITHUB_ENV

      - name: Script that filters the Modules with testing errors
        run: .github/scripts/filter_modules.sh

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'do_pr.txt'

      - name: echo do_pr.txt
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "ISSUE_DESCRIPTION=$(cat do_pr.txt)" >> $GITHUB_ENV

      - name: remove do_pr.txt
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo rm do_pr.txt

      # - name: debug
      #   run: echo $GITHUB_ENV

      # - name: echo do_pr.txt
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   run: cat do_pr.txt

      - name: Debug ISSUE_DESCRIPTION
        run: echo ${{ env.ISSUE_DESCRIPTION }}

      # - name: Make Issue if file exists
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Open new ISSUE on GuillaumeFalourd/poc-github-actions repository
        # if: contains(github.event.label.name , 'documentation')
        if: steps.check_files.outputs.files_exists == 'true'
        uses: GuillaumeFalourd/open-issue-action@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          repo-owner: Research-Project-Glenn-Troncquo
          repo-name: Research-Project-Frontend
          issue-title: Testing failed
          issue-body: ${{ env.ISSUE_DESCRIPTION }}

      - name: curl
        run: |
          curl --request POST --url "https://api.trello.com/1/cards?idList=61f16f2aa1468557c219ebfa&key=74d79d8a81bca9fc82038ff912c6891a&token=2bace6d2535988d020e84a2615964f5f7f26c19c4888f9ce94fe0430850d3d14&name=testingerror" --data-urlencode "desc=$ISSUE_DESCRIPTION"
          

      - name: Create PR title
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "PR_TITLE=[ $NEW_BRANCH ] Modules that passes in all tests" >> $GITHUB_ENV
          rm do_pr.txt

      - name: Debug NEW_BRANCH
        run: echo ${{ env.PR_TITLE }}

      - name: pull-request-action
        if: steps.check_files.outputs.files_exists == 'true'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: ${{ env.NEW_BRANCH }}
          PULL_REQUEST_BRANCH: ${{ env.PARENT_BRANCH }}
          PULL_REQUEST_TITLE: ${{ env.PR_TITLE }}
