name: Filter Modules Workflow

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [feature/**]

jobs:
  filter_modules:
    name: Run Angular testing and filter Modules with testing errors
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15

      - name: Setup
        run: npm ci

      - name: Set CURRENT_BRANCH
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Debug CURRENT_BRANCH
        run: echo ${{ env.CURRENT_BRANCH }}

      - name: Set PARENT_BRANCH
        run: echo "PARENT_BRANCH=develop" >> $GITHUB_ENV

      - name: Debug PARENT_BRANCH
        run: echo ${{ env.CURRENT_BRANCH }}

      - name: Set TIMESTAMP
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Debug Timestamp
        run: echo ${{ env.TIMESTAMP }}

      - name: Set NEW_BRANCH
        run: echo "NEW_BRANCH=${CURRENT_BRANCH}_SUCCESS_${TIMESTAMP}" >> $GITHUB_ENV

      - name: Debug NEW_BRANCH
        run: echo ${{ env.NEW_BRANCH }}

      - name: Script that filters the Modules with testing errors
        run: .github/scripts/filter_modules.sh
