# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Anguler CI/CD

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build_angular:
    runs-on: ubuntu-latest
    name: Run Angular App Through CI/CD Pipeline
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - run: npm ci
      - run: npm run test
      - run: npm run build
