name: Trello Issue List
on:
  issues:
    types: [opened]
env:
  TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
  TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}

jobs:
  issue_send:
    name: Send Issue to Trello
    runs-on: ubuntu-latest
    steps:
      - name: Runs trello manage
        uses: sisodiya2421/trello-manage@master
        with:
          repo-name: ${{ github.repository }}
          trello-username: ${{ secrets.TRELLO_USERNAME }}


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dalezak/github-commit-to-trello-card@main
        with:
          trello-api-key: ${{ secrets.TRELLO_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-board-id: ${{ secrets.TRELLO_BOARD }}
          trello-card-action: "Attachment"
          trello-list-name-commit: "Doing"
          trello-list-name-pr-open: "Reviewing"
          trello-list-name-pr-closed: "Testing"